//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxCollector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxCollector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ada:controlled_amount,xch:mojo.
        /// </summary>
        public static string balance_keywords {
            get {
                return ResourceManager.GetString("balance_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xch:1000000000000,ada:1000000.
        /// </summary>
        public static string balance_multiplier {
            get {
                return ResourceManager.GetString("balance_multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xch|https://xchscan.com/api/account/balance?address=xch1qtkqyhgtm0yc45x8dzc58um2h0eznvzfk26sdlednultsg5nvmcqg07z6r,ada|https://cardano-mainnet.blockfrost.io/api/v0/accounts/stake1u9s6yx9e7fxsq69n59te30hevjthgfrpe3tn7pp4cqclhagdkjhhj.
        /// </summary>
        public static string balanceuri {
            get {
                return ResourceManager.GetString("balanceuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d89cb7f2-3ccb-434f-8cc9-60f1d8a6e00c.
        /// </summary>
        public static string cmcapikey {
            get {
                return ResourceManager.GetString("cmcapikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xch:9258,ada:2010.
        /// </summary>
        public static string cmcids {
            get {
                return ResourceManager.GetString("cmcids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xch,ada.
        /// </summary>
        public static string coins {
            get {
                return ResourceManager.GetString("coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ada:project_id|mainnetPdzq8F5WLgw3xDphokA6fcufWE13Nb67.
        /// </summary>
        public static string headers {
            get {
                return ResourceManager.GetString("headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Chia_App\history.txt.
        /// </summary>
        public static string historyfile {
            get {
                return ResourceManager.GetString("historyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Chia_App\lastamount.txt.
        /// </summary>
        public static string lastamountfile {
            get {
                return ResourceManager.GetString("lastamountfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Chia_App\log.txt.
        /// </summary>
        public static string logfile {
            get {
                return ResourceManager.GetString("logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest.
        /// </summary>
        public static string priceuri {
            get {
                return ResourceManager.GetString("priceuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pro-api.coinmarketcap.com/v2/tools/price-conversion.
        /// </summary>
        public static string priceuriv1 {
            get {
                return ResourceManager.GetString("priceuriv1", resourceCulture);
            }
        }
    }
}
